#!/bin/sh

set -e

# // spark-shell for spark 3.2
# --packages org.apache.hudi:hudi-spark3_2.12:0.10.1,org.apache.spark:spark-avro_2.12:3.2.1 \
HUDI_SPARK_BUNDLE="$HOME/github.com/apache/hudi/packaging/hudi-spark-bundle/target/hudi-spark3.1.2-bundle_2.12-0.10.1.jar"
spark-shell \
    --jars $HUDI_SPARK_BUNDLE \
    --packages org.apache.spark:spark-avro_2.12:3.2.1 \
    --conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer'

# // spark-shell for spark 3.1
# spark-shell \
#   --packages org.apache.hudi:hudi-spark3.1.2-bundle_2.12:0.10.1,org.apache.spark:spark-avro_2.12:3.1.2 \
#   --conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer'
# 
# // spark-shell for spark 3.0
# spark-shell \
#   --packages org.apache.hudi:hudi-spark3.0.3-bundle_2.12:0.10.1,org.apache.spark:spark-avro_2.12:3.0.3 \
#   --conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer'
#   
# // spark-shell for spark 2 with scala 2.12
# spark-shell \
#   --packages org.apache.hudi:hudi-spark-bundle_2.12:0.10.1,org.apache.spark:spark-avro_2.12:2.4.4 \
#   --conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer'
#   
# // spark-shell for spark 2 with scala 2.11
# spark-shell \
#   --packages org.apache.hudi:hudi-spark-bundle_2.11:0.10.1,org.apache.spark:spark-avro_2.11:2.4.4 \
#   --conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer'
